/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package filehandling;

import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        FileHandler handler = new FileHandler("./testDirectory");
        System.out.println(new JsonFolder(handler.getFolder("./testDirectory")));
    }
}
